title: "Digitale-Kollaboration.de"
email: "silvana.heiss@gmail.com"
phone: "+49 176 57886094"
address: 
  street: Agnes Bernauer Straße 47
  city: 80687 München
description: >- # this means to ignore newlines until "baseurl:"
 Selbstbewusst im digitalisierten Büroalltag
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://test.digitale-kollaboration.de" # the base hostname & protocol for your site, e.g. http://example.com or  https://tradejk.netlify.com
#facebook_url: "https://www.facebook.com/jekyll"
#twitter_url: "https://twitter.com/tryghost"
#github_url:  "https://github.com/TryGhost/Ghost"
#pinterest_url: "https://www.pinterest.com/rubel8525"
#linkedin_url: "https://www.linkenin.com/rubel8525"
#instagram_url: "https://www.instagram.com/rubel8525"
#youtube_url: "https://youtube.com/rubel2585"
logo: "/assets/images/logo-digitale-kollaboration2.png"
logo_2: "/assets/images/footer-logo.png"
mailchimp_list: "https://themeix.us16.list-manage.com/subscribe/post?u=307862c135e4548eecf86f389&amp;id=342411fb35"

permalink: "/:title"

copyright_text: "Copyright ©2021. All Rights Reserved"
phone_number: "+49 176 57886094"
cover_image: "/assets/images/page-title-bg.jpg"


# Build settings
sass:
  style: compressed
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-archives

#########################
# paginate plugin v1
paginate: 6
paginate_path: "/blog/page:num/"

tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

jekyll-archives:
  enabled: all
  layout: category
  permalinks:
    category: '/category/:name/'

feed:
  collections:
    posts:
      path: "/index.xml"